yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("about/", include("about.urls")),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright 
  <span style="color:red">Ya</span>tube
</p>    

yatube/templates/includes/forms.html
<div class="card-body">
    {% load user_filters %}
    {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}            
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
        {% endfor %}
    {% endif %}
    <form method="post" enctype="multipart/form-data"
    {% if action_url %}
      action="{% url action_url %}"
    {% endif %}
  >
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group row my-3"
        {% if field.field.required %} 
          aria-required="true"
        {% else %}
          aria-required="false"
        {% endif %}
      >
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
            {% if field.field.required %}
              <span class="required text-danger">*</span>
            {% endif %}
        </label>
        <div>
        {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      </div>
    {% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% include 'includes/list.html' with path='about:author' text='Об авторе' %}
        {% include 'includes/list.html' with path='about:tech' text='Технологии' %}

        {% if user.is_authenticated %}

          {% include 'includes/list.html' with path='posts:post_create' text='Новая запись' %}
          {% include 'includes/list.html' with path='users:password_change' text='Изменить пароль' light='link-light' %}
          {% include 'includes/list.html' with path='users:logout' text='Выйти' light='link-light' %}
          {% include 'includes/list.html' with text='' margin='m-2' %}

        {% else %}

          {% include 'includes/list.html' with path='users:login' text='Войти' light='link-light' %}
          {% include 'includes/list.html' with path='users:signup' text='Регистрация' light='link-light' %}
          
        {% endif %}
      </ul>
    </div>
  </nav>      
</header> 

yatube/templates/includes/list.html
{% with request.resolver_match.view_name as view_name %}
<li class="nav-item {{margin}}"> 
    {% if text == '' %}
       Пользователь: {{user.username}}
    {% else %}
      <a class="nav-link {{light}} {% if view_name == path %} active {% endif %}" 
         href="{% url path %}">
           {{text}}
      </a>
    {% endif %}
  </li>
{% endwith %}